

### Variables
@baseUrl = http://localhost:3000
#@baseUrl = https://quest4kids-a7fd24f91954.herokuapp.com
@contentType = application/json

### The basic request
GET {{baseUrl}}

### Profile
GET {{baseUrl}}/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1OTdmZTRlNC1mYjUxLTQ5MzQtOTdjZi0yYTU2N2NmYWYwZTYiLCJuYW1lIjoibXlzaGFyeXNoIiwicm9sZSI6InBhcmVudCIsImlhdCI6MTc0MDY1MzAxMSwiZXhwIjoxNzQwNjU2NjExfQ.tu0v1n0ot6VyCMqBQYEmIiVzlrwlWuuJt0qriohzkcc


### Parent Only
GET {{baseUrl}}/auth/parent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGRiZDRhMC1lY2JhLTQ1MzgtYTcwOC1mMmRmZDc4OTU2ZWYiLCJuYW1lIjoibXlzaGFyeXNoIiwicm9sZSI6InBhcmVudCIsImlhdCI6MTc0MDU4NDM3NywiZXhwIjoxNzQwNTg3OTc3fQ.5o-mAiVIa9-OfxoM0n5JrXpHRmCFfEjbM8BLKBB84mc


### Register
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "email": "test3@gmail.com",
  "name": "mysharysh3",
  "password": "Test123!"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "test@gmail.com",
  "password": "Test123!"
}

### Create child account
POST {{baseUrl}}/user/create-child-account
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1OTdmZTRlNC1mYjUxLTQ5MzQtOTdjZi0yYTU2N2NmYWYwZTYiLCJuYW1lIjoibXlzaGFyeXNoIiwicm9sZSI6InBhcmVudCIsImlhdCI6MTc0MDY1MzAxMSwiZXhwIjoxNzQwNjU2NjExfQ.tu0v1n0ot6VyCMqBQYEmIiVzlrwlWuuJt0qriohzkcc

{
  "email": "child2@gmail.com",
  "name": "Fedor",
  "password": "Test123!"
}

### Get children list
GET  {{baseUrl}}/user/get-children-list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1OTdmZTRlNC1mYjUxLTQ5MzQtOTdjZi0yYTU2N2NmYWYwZTYiLCJuYW1lIjoibXlzaGFyeXNoIiwicm9sZSI6InBhcmVudCIsImlhdCI6MTc0MDY1MzAxMSwiZXhwIjoxNzQwNjU2NjExfQ.tu0v1n0ot6VyCMqBQYEmIiVzlrwlWuuJt0qriohzkcc



### Get all tasks 
# @name getAllTasks
GET {{baseUrl}}/tasks?limit=2&offset=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGRiZDRhMC1lY2JhLTQ1MzgtYTcwOC1mMmRmZDc4OTU2ZWYiLCJuYW1lIjoibXlzaGFyeXNoIiwicm9sZSI6InBhcmVudCIsImlhdCI6MTc0MDU4NDM3NywiZXhwIjoxNzQwNTg3OTc3fQ.5o-mAiVIa9-OfxoM0n5JrXpHRmCFfEjbM8BLKBB84mc

### Get all IN_PROGRESS tasks 
# @name getAllInProgress
GET {{baseUrl}}/tasks?status=IN_PROGRESS
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzI2MDYwMS1iNGU5LTQwOTAtYmE4Yy1kOWMwYTc3OWI3MzMiLCJuYW1lIjoibXlzaGFyeXNoIiwiaWF0IjoxNzQwNDgxNTMyLCJleHAiOjE3NDA0ODUxMzJ9.aDNXZkhMbVbkFwx1zKyZeY8-G1lIaiO4xdYS3-dM34c


### Get all with search query 
# @name getAllWithSearchQuery
GET {{baseUrl}}/tasks?search=Nest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzI2MDYwMS1iNGU5LTQwOTAtYmE4Yy1kOWMwYTc3OWI3MzMiLCJuYW1lIjoibXlzaGFyeXNoIiwiaWF0IjoxNzQwNDgxNTMyLCJleHAiOjE3NDA0ODUxMzJ9.aDNXZkhMbVbkFwx1zKyZeY8-G1lIaiO4xdYS3-dM34c


### Get all filtered by labels
# @name getAllFilteredByLabels
GET {{baseUrl}}/tasks?labels=bug
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzI2MDYwMS1iNGU5LTQwOTAtYmE4Yy1kOWMwYTc3OWI3MzMiLCJuYW1lIjoibXlzaGFyeXNoIiwiaWF0IjoxNzQwNDg2MDM0LCJleHAiOjE3NDA0ODk2MzR9.oKnnY6Z6XGYkFHDds8DjPKg8hkZxDD6XhWmt3AZOnR8

### Get all sorted
# @name getAllSorted
GET {{baseUrl}}/tasks?sortBy=createdAt&sortOrder=DESC
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzI2MDYwMS1iNGU5LTQwOTAtYmE4Yy1kOWMwYTc3OWI3MzMiLCJuYW1lIjoibXlzaGFyeXNoIiwiaWF0IjoxNzQwNDg2MDM0LCJleHAiOjE3NDA0ODk2MzR9.oKnnY6Z6XGYkFHDds8DjPKg8hkZxDD6XhWmt3AZOnR8


### Get one task
#GET {{baseUrl}}/tasks/{{taskId}}
GET {{baseUrl}}/tasks/20ab1583-f3cd-4497-985f-9d855cd87df4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGRiZDRhMC1lY2JhLTQ1MzgtYTcwOC1mMmRmZDc4OTU2ZWYiLCJuYW1lIjoibXlzaGFyeXNoIiwicm9sZSI6InBhcmVudCIsImlhdCI6MTc0MDU4NDM3NywiZXhwIjoxNzQwNTg3OTc3fQ.5o-mAiVIa9-OfxoM0n5JrXpHRmCFfEjbM8BLKBB84mc

### Create new task
# @name createTask
POST {{baseUrl}}/tasks
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MGRiZDRhMC1lY2JhLTQ1MzgtYTcwOC1mMmRmZDc4OTU2ZWYiLCJuYW1lIjoibXlzaGFyeXNoIiwicm9sZSI6InBhcmVudCIsImlhdCI6MTc0MDU4NDM3NywiZXhwIjoxNzQwNTg3OTc3fQ.5o-mAiVIa9-OfxoM0n5JrXpHRmCFfEjbM8BLKBB84mc

{
  "title": "Mysha",
  "description": "Mysha Description",
  "status": "OPEN",
  "labels": [
    {
      "name": "Mysha label"
    }
  ]
}
### Set the task id
@taskId = {{ createTask.response.body.id }}

### Update the task status
PATCH {{baseUrl}}/tasks/{{taskId}}
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzI2MDYwMS1iNGU5LTQwOTAtYmE4Yy1kOWMwYTc3OWI3MzMiLCJuYW1lIjoibXlzaGFyeXNoIiwiaWF0IjoxNzQwNDczNjgwLCJleHAiOjE3NDA0NzcyODB9.xsCtheYmx43HJm5SpI9ARWMCV7Urb9ztT69S-YhkTbg


{
  "status": "IN_PROGRESS",
  "labels": [{
    "name": "done"
  }]
}

### Deleting a task
DELETE {{ baseUrl }}/tasks/{{taskId}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzI2MDYwMS1iNGU5LTQwOTAtYmE4Yy1kOWMwYTc3OWI3MzMiLCJuYW1lIjoibXlzaGFyeXNoIiwiaWF0IjoxNzQwNDczNjgwLCJleHAiOjE3NDA0NzcyODB9.xsCtheYmx43HJm5SpI9ARWMCV7Urb9ztT69S-YhkTbg


### Add specific labels to task
# @name addLabels
POST {{baseUrl}}/tasks/{{taskId}}/labels
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzI2MDYwMS1iNGU5LTQwOTAtYmE4Yy1kOWMwYTc3OWI3MzMiLCJuYW1lIjoibXlzaGFyeXNoIiwiaWF0IjoxNzQwNDczNjgwLCJleHAiOjE3NDA0NzcyODB9.xsCtheYmx43HJm5SpI9ARWMCV7Urb9ztT69S-YhkTbg


[
  {"name": "prioritized"},
  {"name": "bug"}
]

### Remove specific labels from task
# @name removeLabels
DELETE {{baseUrl}}/tasks/{{taskId}}/labels
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzI2MDYwMS1iNGU5LTQwOTAtYmE4Yy1kOWMwYTc3OWI3MzMiLCJuYW1lIjoibXlzaGFyeXNoIiwiaWF0IjoxNzQwNDczNjgwLCJleHAiOjE3NDA0NzcyODB9.xsCtheYmx43HJm5SpI9ARWMCV7Urb9ztT69S-YhkTbg


["prioritized"]