### Variables
@baseUrl = http://localhost:3000
#@baseUrl = https://quest4kids-a7fd24f91954.herokuapp.com
@contentType = application/json

### The basic request
GET {{baseUrl}}

### Profile
GET {{baseUrl}}/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1OTdmZTRlNC1mYjUxLTQ5MzQtOTdjZi0yYTU2N2NmYWYwZTYiLCJuYW1lIjoibXlzaGFyeXNoIiwicm9sZSI6InBhcmVudCIsImlhdCI6MTc0MDY2NTAxNiwiZXhwIjoxNzQwNjY4NjE2fQ.Zj-0BhU-uBZ0SJ6yn1p-EqGRnI9fsXD3FkM6KRktm6M


### Register
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "email": "test3@gmail.com",
  "name": "mysharysh3",
  "password": "Test123!"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "test@gmail.com",
  "password": "Test123!"
}

### Create child account
POST {{baseUrl}}/user/create-child-account
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5N2ZlNGU0LWZiNTEtNDkzNC05N2NmLTJhNTY3Y2ZhZjBlNiIsIm5hbWUiOiJteXNoYXJ5c2giLCJyb2xlIjoicGFyZW50IiwiaWF0IjoxNzQxMTc5MzI3LCJleHAiOjE3NDExODI5Mjd9.omkbddfIYKmIVOIWF94JOcXXgpAiNexLD0L_rjOkSSY

{
  "email": "sergey@gmail.com",
  "name": "Sergey",
  "password": "Test123!"
}

### Get children list
GET  {{baseUrl}}/user/get-children-list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5N2ZlNGU0LWZiNTEtNDkzNC05N2NmLTJhNTY3Y2ZhZjBlNiIsIm5hbWUiOiJteXNoYXJ5c2giLCJyb2xlIjoicGFyZW50IiwiaWF0IjoxNzQxMTc5MzI3LCJleHAiOjE3NDExODI5Mjd9.omkbddfIYKmIVOIWF94JOcXXgpAiNexLD0L_rjOkSSY


### Get child account
GET {{baseUrl}}/user/get-child-account/de30c98e-1b0d-481f-b245-764d347bb232
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5N2ZlNGU0LWZiNTEtNDkzNC05N2NmLTJhNTY3Y2ZhZjBlNiIsIm5hbWUiOiJteXNoYXJ5c2giLCJyb2xlIjoicGFyZW50IiwiaWF0IjoxNzQxMTc5MzI3LCJleHAiOjE3NDExODI5Mjd9.omkbddfIYKmIVOIWF94JOcXXgpAiNexLD0L_rjOkSSY

### Update child account
PATCH  {{baseUrl}}/user/update-child-account/de30c98e-1b0d-481f-b245-764d347bb232
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5N2ZlNGU0LWZiNTEtNDkzNC05N2NmLTJhNTY3Y2ZhZjBlNiIsIm5hbWUiOiJteXNoYXJ5c2giLCJyb2xlIjoicGFyZW50IiwiaWF0IjoxNzQxMTc5MzI3LCJleHAiOjE3NDExODI5Mjd9.omkbddfIYKmIVOIWF94JOcXXgpAiNexLD0L_rjOkSSY

{
  "name": "Sergey2",
  "email": "sergey2@gmail.com"
}


### Delete child account
DELETE  {{baseUrl}}/user/remove-child-account/de30c98e-1b0d-481f-b245-764d347bb232
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5N2ZlNGU0LWZiNTEtNDkzNC05N2NmLTJhNTY3Y2ZhZjBlNiIsIm5hbWUiOiJteXNoYXJ5c2giLCJyb2xlIjoicGFyZW50IiwiaWF0IjoxNzQxMTc5MzI3LCJleHAiOjE3NDExODI5Mjd9.omkbddfIYKmIVOIWF94JOcXXgpAiNexLD0L_rjOkSSY




### Get all tasks 
# @name getAllTasks
GET {{baseUrl}}/tasks?limit=10&offset=0&childId=e7f0c34a-e79c-4980-9e0b-0a932a7f4706
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5N2ZlNGU0LWZiNTEtNDkzNC05N2NmLTJhNTY3Y2ZhZjBlNiIsIm5hbWUiOiJteXNoYXJ5c2giLCJyb2xlIjoicGFyZW50IiwiaWF0IjoxNzQxMTc5MzI3LCJleHAiOjE3NDExODI5Mjd9.omkbddfIYKmIVOIWF94JOcXXgpAiNexLD0L_rjOkSSY


### Get all IN_PROGRESS tasks 
# @name getAllInProgress
GET {{baseUrl}}/tasks?status=IN_PROGRESS
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzI2MDYwMS1iNGU5LTQwOTAtYmE4Yy1kOWMwYTc3OWI3MzMiLCJuYW1lIjoibXlzaGFyeXNoIiwiaWF0IjoxNzQwNDgxNTMyLCJleHAiOjE3NDA0ODUxMzJ9.aDNXZkhMbVbkFwx1zKyZeY8-G1lIaiO4xdYS3-dM34c


### Get all with search query 
# @name getAllWithSearchQuery
GET {{baseUrl}}/tasks?search=Nest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzI2MDYwMS1iNGU5LTQwOTAtYmE4Yy1kOWMwYTc3OWI3MzMiLCJuYW1lIjoibXlzaGFyeXNoIiwiaWF0IjoxNzQwNDgxNTMyLCJleHAiOjE3NDA0ODUxMzJ9.aDNXZkhMbVbkFwx1zKyZeY8-G1lIaiO4xdYS3-dM34c


### Get all filtered by labels
# @name getAllFilteredByLabels
GET {{baseUrl}}/tasks?labels=bug
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzI2MDYwMS1iNGU5LTQwOTAtYmE4Yy1kOWMwYTc3OWI3MzMiLCJuYW1lIjoibXlzaGFyeXNoIiwiaWF0IjoxNzQwNDg2MDM0LCJleHAiOjE3NDA0ODk2MzR9.oKnnY6Z6XGYkFHDds8DjPKg8hkZxDD6XhWmt3AZOnR8

### Get all sorted
# @name getAllSorted
GET {{baseUrl}}/tasks?sortBy=createdAt&sortOrder=DESC
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzI2MDYwMS1iNGU5LTQwOTAtYmE4Yy1kOWMwYTc3OWI3MzMiLCJuYW1lIjoibXlzaGFyeXNoIiwiaWF0IjoxNzQwNDg2MDM0LCJleHAiOjE3NDA0ODk2MzR9.oKnnY6Z6XGYkFHDds8DjPKg8hkZxDD6XhWmt3AZOnR8


### Get one task
#GET {{baseUrl}}/tasks/{{taskId}}
GET {{baseUrl}}/tasks/b516c069-5e2f-4eeb-bac1-dd62930e677a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5N2ZlNGU0LWZiNTEtNDkzNC05N2NmLTJhNTY3Y2ZhZjBlNiIsIm5hbWUiOiJteXNoYXJ5c2giLCJyb2xlIjoicGFyZW50IiwiaWF0IjoxNzQwNjczNjk2LCJleHAiOjE3NDA2NzcyOTZ9.6bcfnGDMPfERWtPAP9eKVr8MDXOr1iHdtgvW591bk1c

### Create new task
# @name createTask
POST {{baseUrl}}/kids/2342c256-e93d-495f-bfeb-f119ad242a39/task
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5N2ZlNGU0LWZiNTEtNDkzNC05N2NmLTJhNTY3Y2ZhZjBlNiIsIm5hbWUiOiJteXNoYXJ5c2giLCJyb2xlIjoicGFyZW50IiwiaWF0IjoxNzQwNjcwMDQ4LCJleHAiOjE3NDA2NzM2NDh9.ktB-OId3rMtx3Ob6sudcgOvF1ow1u26yFdaxdiKgV1I

{
  "title": "Test1",
  "description": "Test Description",
  "status": "OPEN",
  "labels": [
    {
      "name": "Test label"
    }
  ]
}

### Set the task id
@taskId = {{ createTask.response.body.id }}

### Update the task status
PATCH {{baseUrl}}/tasks/d39ab36a-a053-4bba-b597-1b62df4c5e51
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5N2ZlNGU0LWZiNTEtNDkzNC05N2NmLTJhNTY3Y2ZhZjBlNiIsIm5hbWUiOiJteXNoYXJ5c2giLCJyb2xlIjoicGFyZW50IiwiaWF0IjoxNzQxMTc5MzI3LCJleHAiOjE3NDExODI5Mjd9.omkbddfIYKmIVOIWF94JOcXXgpAiNexLD0L_rjOkSSY

{
  "title": "Mysha2"
}

### Deleting a task
DELETE {{ baseUrl }}/tasks/{{taskId}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzI2MDYwMS1iNGU5LTQwOTAtYmE4Yy1kOWMwYTc3OWI3MzMiLCJuYW1lIjoibXlzaGFyeXNoIiwiaWF0IjoxNzQwNDczNjgwLCJleHAiOjE3NDA0NzcyODB9.xsCtheYmx43HJm5SpI9ARWMCV7Urb9ztT69S-YhkTbg


### Add specific labels to task
# @name addLabels
POST {{baseUrl}}/tasks/{{taskId}}/labels
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzI2MDYwMS1iNGU5LTQwOTAtYmE4Yy1kOWMwYTc3OWI3MzMiLCJuYW1lIjoibXlzaGFyeXNoIiwiaWF0IjoxNzQwNDczNjgwLCJleHAiOjE3NDA0NzcyODB9.xsCtheYmx43HJm5SpI9ARWMCV7Urb9ztT69S-YhkTbg


[
  {"name": "prioritized"},
  {"name": "bug"}
]

### Remove specific labels from task
# @name removeLabels
DELETE {{baseUrl}}/tasks/{{taskId}}/labels
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzI2MDYwMS1iNGU5LTQwOTAtYmE4Yy1kOWMwYTc3OWI3MzMiLCJuYW1lIjoibXlzaGFyeXNoIiwiaWF0IjoxNzQwNDczNjgwLCJleHAiOjE3NDA0NzcyODB9.xsCtheYmx43HJm5SpI9ARWMCV7Urb9ztT69S-YhkTbg


["prioritized"]