### Variables

@baseUrl = http://localhost:3000
#@baseUrl = https://quest4kids-a7fd24f91954.herokuapp.com
#@baseUrl = http://quest4kids-api.us-east-1.elasticbeanstalk.com
@contentType = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZhNjZmMjYxLWNmNGQtNDA0OC1hMjBiLTdhZjI3NTliNTk1YSIsIm5hbWUiOiJqb2huIGRvdSIsInJvbGUiOiJwYXJlbnQiLCJpYXQiOjE3NDgzNTA3MTAsImV4cCI6MTc0ODM1NDMxMH0.ZXCP5yDMT20mfxQXvtIGhG4_uqBrDCO8IKWxh7P0NFc

### The basic request
GET {{baseUrl}}

### Profile
GET {{baseUrl}}/auth/profile
Authorization: Bearer {{token}}

### Register
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "email": "test@gmail.com",
  "name": "john dou",
  "password": "Test123!"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "test@gmail.com",
  "password": "Test123!"
}

### Refresh
POST {{baseUrl}}/auth/refresh
Content-Type: {{contentType}}

{
  "token": {{token}}
}

### Create child account
POST {{baseUrl}}/user/create-child-account
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "email": "sergey@gmail.com",
  "name": "Sergey",
  "password": "Test123!"
}

### Get children list
GET  {{baseUrl}}/user/get-children-list
Authorization: Bearer {{token}}

### Get child account
GET {{baseUrl}}/user/get-child-account/de30c98e-1b0d-481f-b245-764d347bb232
Authorization: Bearer {{token}}

### Update child account
PATCH  {{baseUrl}}/user/update-child-account/de30c98e-1b0d-481f-b245-764d347bb232
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "name": "Sergey2",
  "email": "sergey2@gmail.com"
}


### Delete child account
DELETE  {{baseUrl}}/user/remove-child-account/de30c98e-1b0d-481f-b245-764d347bb232
Authorization: Bearer {{token}}




### Get all tasks 
# @name getAllTasks
GET {{baseUrl}}/tasks?limit=10&offset=0&childId=bf54b043-3891-4ac0-8a44-a698e682b79b
Authorization: Bearer {{token}}


### Get all IN_PROGRESS tasks 
# @name getAllInProgress
GET {{baseUrl}}/tasks?status=IN_PROGRESS
Authorization: Bearer {{token}}


### Get all with search query 
# @name getAllWithSearchQuery
GET {{baseUrl}}/tasks?search=Nest
Authorization: Bearer {{token}}


### Get all filtered by labels
# @name getAllFilteredByLabels
GET {{baseUrl}}/tasks?labels=bug
Authorization: Bearer {{token}}

### Get all sorted
# @name getAllSorted
GET {{baseUrl}}/tasks?sortBy=createdAt&sortOrder=DESC
Authorization: Bearer {{token}}


### Get one task
#GET {{baseUrl}}/tasks/{{taskId}}
GET {{baseUrl}}/tasks/366cbef7-6094-4023-a3f5-22a2161dd34f
Authorization: Bearer {{token}}

### Create new task
# @name createTask
POST {{baseUrl}}/kids/bf54b043-3891-4ac0-8a44-a698e682b79b/task
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "title": "Test1",
  "description": "Test Description",
  "status": "OPEN",
  "labels": ["School"],
  "estimatedTime": 60,
  "actualTime": 0,
  "comment": "init comment"
}

### Set the task id
@taskId = {{ createTask.response.body.id }}

### Update the task status
PATCH {{baseUrl}}/tasks/52fc93b0-bd32-4106-92f0-7636fdc8c765
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "status": "DONE",
  "comment": "finish"
}

### Deleting a task
DELETE {{ baseUrl }}/tasks/{{taskId}}
Authorization: Bearer {{token}}


### Add specific labels to task
# @name addLabels
POST {{baseUrl}}/tasks/{{taskId}}/labels
Content-Type: {{contentType}}
Authorization: Bearer {{token}}


[
  {"name": "prioritized"},
  {"name": "bug"}
]

### Remove specific labels from task
# @name removeLabels
DELETE {{baseUrl}}/tasks/{{taskId}}/labels
Content-Type: {{contentType}}
Authorization: Bearer {{token}}


["prioritized"]