import { DashboardElement } from './dashboard-settings.entity';

export const defaultDashboardLayout: DashboardElement[] = [
  {
    w: 5,
    h: 4,
    x: 0,
    y: 0,
    i: 'taskByChildren',
    minH: 3,
    maxH: undefined,
    minW: undefined,
    maxW: undefined,
    moved: false,
    static: false,
    isResizable: true,
    isDraggable: true,
    isVisible: true,
  },
  {
    w: 7,
    h: 3,
    x: 5,
    y: 2,
    i: 'countOfTasks',
    minH: 3,
    maxH: undefined,
    minW: undefined,
    maxW: undefined,
    moved: false,
    static: false,
    isResizable: true,
    isDraggable: true,
    isVisible: true,
  },
  {
    w: 7,
    h: 2,
    x: 5,
    y: 0,
    i: 'children',
    minH: 2,
    maxH: undefined,
    minW: undefined,
    maxW: undefined,
    moved: false,
    static: false,
    isResizable: true,
    isDraggable: true,
    isVisible: true,
  },
  {
    w: 5,
    h: 3,
    x: 0,
    y: 4,
    i: 'weather',
    minH: 0,
    maxH: undefined,
    minW: undefined,
    maxW: undefined,
    moved: false,
    static: false,
    isResizable: true,
    isDraggable: true,
    isVisible: true,
  },
];
