apiVersion: apps/v1
kind: Deployment
metadata:
  name: quest4kids-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quest4kids-api
  template:
    metadata:
      name: quest4kids-api
      labels:
        app: quest4kids-api
    spec:
      containers:
        - name: quest4kids-api-container
          image: CONTAINER_IMAGE  # Path for image in ECR
          env:
            - name: NODE_ENV
              value: production
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: db-url
            - name: AMAZON_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: aws-access-key            
            - name: AMAZON_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: aws-s3-sec
            - name: APP_MESSAGE_PREFIX
              value: "from EKS" 
            - name: DB_SYNC
              value: "0"
            - name: EMAIL_HOST
              value: smtp.gmail.com     
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: email-pass
            - name: EMAIL_USERNAME
              value: quest4kidsmys@gmail.com    
            - name: GOOGLE_CALLBACK_URL
              value: https://api-quest4kids.venturisoft.com/auth/google/callback  # need update api  real url    
            - name: GOOGLE_CLIENT_ID
              value: 627594459419-nfncpevikr449fpvlauusr7d05783jtq.apps.googleusercontent.com     
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: google-client-sec
            - name: JWT_EXPIRES_IN
              value: 60m
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: jwt-sec
            - name: AMAZON_BUCKET
              value: my-nest-bucket-test
            - name: URL_RESET_PASSWORD
              value: "https://venturisoft.com/auth/reset-password" # need update real front url

          ports:
            - containerPort: 3000
          
